### 베르누이 나이브베이즈
- 데이터 : https://www.kaggle.com/team-ai/spam-text-message-classification

In [1]:
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("spam.csv")
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [4]:
data["label"] =data["Category"].map({"spam":1,"ham":0})
data.head()

Category                                            Message  label
0      ham  Go until jurong point, crazy.. Available only ...      0
1      ham                      Ok lar... Joking wif u oni...      0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3      ham  U dun say so early hor... U c already then say...      0
4      ham  Nah I don't think he goes to usf, he lives aro...      0

In [20]:
X = data["Message"]
y = data["label"]

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state = 103)

print(x_train.shape,x_test.shape,y_train.shape, y_test.shape)

(3900,) (1672,) (3900,) (1672,)


In [21]:
 #최대 단어 1000개, 토큰화 따로 지정x -> 내장 토큰화는 띄어쓰기 기준
# 이진 모델로 지정 binary
cv = CountVectorizer(max_features = 1000,binary =True)
x_train_cv = cv.fit_transform(x_train)

In [22]:
encoded = x_train_cv.toarray()
encoded

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
cv.inverse_transform(encoded[0])

[array(['and', 'come', 'down', 'face', 'feel', 'for', 'have', 'heart',
        'into', 'life', 'loved', 'making', 'me', 'my', 'on', 'smile',
        'sun', 'the', 'you'], dtype='<U15')]

In [31]:
print(cv.get_feature_names())


['000', '04', '0800', '08000839402', '08000930705', '08712460324', '10', '100', '1000', '10p', '11', '12hrs', '150', '150p', '150ppm', '16', '18', '1st', '20', '200', '2000', '2003', '250', '2day', '2lands', '2nd', '30', '350', '50', '500', '5000', '50p', '750', '800', '8007', '86688', '87066', 'able', 'about', 'abt', 'ac', 'account', 'across', 'actually', 'address', 'aft', 'after', 'afternoon', 'again', 'age', 'age16', 'ago', 'ah', 'aight', 'all', 'almost', 'alone', 'already', 'alright', 'also', 'always', 'am', 'amp', 'an', 'and', 'angry', 'another', 'ans', 'answer', 'any', 'anyone', 'anything', 'anytime', 'anyway', 'apply', 'ard', 'are', 'area', 'around', 'as', 'asap', 'ask', 'askd', 'asked', 'ass', 'at', 'attempt', 'auction', 'available', 'await', 'award', 'awarded', 'away', 'awesome', 'b4', 'babe', 'baby', 'back', 'bad', 'bak', 'balance', 'bank', 'bath', 'bb', 'bcoz', 'be', 'beautiful', 'because', 'bed', 'been', 'before', 'being', 'believe', 'best', 'better', 'between', 'big', 'bir

In [12]:
len(cv.get_feature_names())

1000

#### 베르누이 나이브베이즈 분류

In [13]:
nb_clf = BernoulliNB()

nb_clf.fit(x_train_cv, y_train)

BernoulliNB()

In [16]:
x_test_cv = cv.fit_transform(x_test)

In [17]:
print(x_test_cv)

  (0, 840)	1
  (0, 252)	1
  (0, 823)	1
  (0, 832)	1
  (0, 834)	1
  (0, 603)	1
  (0, 82)	1
  (0, 318)	1
  (0, 312)	1
  (0, 236)	1
  (0, 773)	1
  (0, 90)	1
  (0, 61)	1
  (0, 465)	1
  (0, 589)	1
  (1, 940)	1
  (1, 786)	1
  (1, 615)	1
  (2, 789)	1
  (2, 214)	1
  (2, 859)	1
  (2, 970)	1
  (2, 187)	1
  (2, 858)	1
  (2, 652)	1
  :	:
  (1669, 45)	1
  (1669, 508)	1
  (1669, 434)	1
  (1669, 643)	1
  (1669, 529)	1
  (1669, 237)	1
  (1669, 451)	1
  (1670, 897)	1
  (1670, 610)	1
  (1670, 609)	1
  (1670, 923)	1
  (1670, 273)	1
  (1671, 834)	1
  (1671, 90)	1
  (1671, 422)	1
  (1671, 148)	1
  (1671, 599)	1
  (1671, 532)	1
  (1671, 995)	1
  (1671, 607)	1
  (1671, 957)	1
  (1671, 571)	1
  (1671, 69)	1
  (1671, 138)	1
  (1671, 943)	1


In [15]:
encoded2 = x_test_cv.toarray()
encoded2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
pred = nb_clf.predict(x_test_cv)

In [19]:
accuracy_score(y_test,pred)

0.8086124401913876

### < 과제 >
- 베르누이 나이브베이즈 분류 모델을 사용하여 스팸 메세지 분류
- 정제, 필터링 작업 후 분류하여 성능확인

In [45]:
import pandas as pd
from bs4 import BeautifulSoup
import nltk
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
import pickle
import re
import numpy as np


def clean_english_documents(documents):
    #텍스트 정제 (HTML 태그 제거)
    for i, document in enumerate(documents):
        document = BeautifulSoup(document, 'html.parser').text 
        documents[i] = document

    #텍스트 정제 (특수기호 제거)
    for i, document in enumerate(documents):
        document = re.sub(r'[^ A-Za-z]', '', document) #특수기호 제거, 정규 표현식 
        documents[i] = document

    #텍스트 정제 (불용어 제거)
    nltk.download('punkt')
    nltk.download('stopwords')
    for i, document in enumerate(documents):
        clean_words = []
        for word in nltk.tokenize.word_tokenize(document):
            word = word.lower()
            if word not in nltk.corpus.stopwords.words('english'): #불용어 제거
                clean_words.append(word)
        document = ' '.join(clean_words)
        documents[i] = document

    #텍스트 정제 (형태소 분석)
    nltk.download('averaged_perceptron_tagger')
    for i, document in enumerate(documents):
        clean_words = []
        for word in nltk.tag.pos_tag(nltk.tokenize.word_tokenize(document)):
            if word[1] in ['NN', 'NNS', 'NNP', 'NNPS', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'JJ', 'JJR', 'JJS']: #명사, 동사, 형용사
                clean_words.append(word[0])
        document = ' '.join(clean_words)
        document = document.lower()
        documents[i] = document

    #텍스트 정제 (어간 추출)
    for i, document in enumerate(documents):
        clean_words = []
        for word in nltk.tokenize.word_tokenize(document):
            word = word.lower()
            stemmer = nltk.stem.snowball.SnowballStemmer('english')
            word = stemmer.stem(word) #어간 추출
            clean_words.append(word)
        document = ' '.join(clean_words)
        documents[i] = document

    return documents

##########데이터 로드
data = pd.read_csv("spam.csv")
data.head()

data["label"] =data["Category"].map({"spam":1,"ham":0})
data.head()

X = data["Message"]
y = data["label"]

      
      
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state = 103)
print(x_train.shape,x_test.shape,y_train.shape, y_test.shape)

#최대 단어 1000개, 토큰화 따로 지정x -> 내장 토큰화는 띄어쓰기 기준
# 이진 모델로 지정 binary
cv = CountVectorizer(max_features = 1000,binary =True)
x_train_cv = cv.fit_transform(x_train)

encoded2 = x_test_cv.toarray()
print(encoded2)
print(cv.inverse_transform(encoded[0]))
print(cv.get_feature_names())


pred = nb_clf.predict(x_test_cv)

x_data = np.array(X)
y_data = np.array(y)

labels = ['1', '0']

##########데이터 분석

##########데이터 전처리

x_data = clean_english_documents(x_data) #텍스트 정제
transformer = TfidfVectorizer()
transformer.fit(x_data)
x_data = transformer.transform(x_data) #단어 카운트 가중치

x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=777, stratify=y_data)

##########모델 생성

model = BernoulliNB(alpha=1.0)

##########모델 학습

model.fit(x_train, y_train)

##########모델 검증

print(model.score(x_test, y_test)) #1.0

##########모델 예측

x_test = x
x_test = clean_english_documents(x_test) #텍스트 정제
x_test = transformer.transform(x_test) #단어 카운트 가중치

y_predict = model.predict(x_test)
label = labels[y_predict[0]]
y_predict = model.predict_proba(x_test)
confidence = y_predict[0][y_predict[0].argmax()]

print(label, confidence) 

(3900,) (1672,) (3900,) (1672,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[array(['and', 'come', 'down', 'face', 'feel', 'for', 'have', 'heart',
       'into', 'life', 'loved', 'making', 'me', 'my', 'on', 'smile',
       'sun', 'the', 'you'], dtype='<U15')]
['000', '04', '0800', '08000839402', '08000930705', '08712460324', '10', '100', '1000', '10p', '11', '12hrs', '150', '150p', '150ppm', '16', '18', '1st', '20', '200', '2000', '2003', '250', '2day', '2lands', '2nd', '30', '350', '50', '500', '5000', '50p', '750', '800', '8007', '86688', '87066', 'able', 'about', 'abt', 'ac', 'account', 'across', 'actually', 'address', 'aft', 'after', 'afternoon', 'again', 'age', 'age16', 'ago', 'ah', 'aight', 'all', 'almost', 'alone', 'already', 'alright', 'also', 'always', 'am', 'amp', 'an', 'and', 'angry', 'another', 'ans', 'answer', 'any', 'anyone', 'anything', 'anytime', 'anyway', 'apply', 'ard', 'are', 'area', 'around'

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\rkwjs\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rkwjs\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


KeyboardInterrupt: 