### 나이브베이즈
#### iris 분류

- from sklearn.naive_bayes import GaussianNB

In [2]:
import numpy as np
import pandas as pd


from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
iris_df = pd.DataFrame(iris.data,columns= iris.feature_names)
iris_df["target"] =pd.DataFrame(iris.target)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [8]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [10]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,train_size =0.7,test_size=0.3,random_state =102)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(105, 4) (45, 4) (105,) (45,)


In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
clf = GaussianNB()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
y_pred

array([0, 2, 1, 1, 2, 0, 0, 0, 1, 1, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2,
       1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1,
       2])

In [13]:
clf.predict_proba(iris.data)[[0,30,100]]
#확률값 index로 지정해주기 

array([[1.00000000e+000, 1.04711830e-020, 4.12667192e-028],
       [1.00000000e+000, 1.09684021e-018, 1.73718670e-026],
       [9.62887924e-207, 4.40273357e-012, 1.00000000e+000]])

In [14]:
clf.predict(iris.data)[[0,30,100]]

array([0, 0, 2])

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [16]:
cfmat =confusion_matrix(y_test,y_pred)
print(cfmat)

[[17  0  0]
 [ 0 10  2]
 [ 0  2 14]]


In [17]:
acc = accuracy_score(y_test,y_pred)
print(acc)

0.9111111111111111


- prior 추가

In [19]:
clf2 = GaussianNB(priors = [1/100,1/100,98,100])
clf2.fit(x_train,y_train)

y_pred2 = clf2.predict(x_test)
cfmat2 = confusion_matrix(y_test,y_pred2)
print(cfmat2)


ValueError: Number of priors must match number of classes.

In [18]:
print(cfmat)

[[17  0  0]
 [ 0 10  2]
 [ 0  2 14]]
